title: CMIP Greenhouse Gas (GHG) Concentration Historical Dataset
author: "Zebedee Nicholls, Florence Bockting, Mika Pfl\xFCger"
description: This book contains the deliverables related to the CMIP forcings project.
execute:
  execute_notebooks: cache
  timeout: 300
only_build_toc_files: true
latex:
  use_jupyterbook_latex: true
  latex_engine: xelatex
  latex_elements:
    tocdepth: 4
    preamble: '\setcounter{tocdepth}{4} '
bibtex_bibfiles:
- references.bib
repository:
  url: https://github.com/climate-resource/CMIP7-GHG-Concentration-Manuscripts
  path_to_book: book
  branch: main
html:
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  exclude_patterns:
  - '**.ipynb'
sphinx:
  config:
    latex_elements:
      preamble: "\\usepackage[backend=biber, style=apa]{biblatex} \n\\addbibresource{references.bib}\n\
        \n\\addto\\captionsenglish{\\renewcommand{\\figurename}{Figure }}"
